#!/bin/sh
# build-hpkg.sh
#
# Copyright (c) 2026 Andrea Bernardi. Licenza MIT (vedi LICENSE alla
# radice del repository).
#
# Costruisce un .hpkg locale per un primo test di installazione, senza
# passare da haikuporter/atomo123-0.2.9.recipe: quella recipe richiede
# un tag + checksum SHA256 reale dell'archivio sorgente pubblicato su
# GitHub per QUESTA versione, che non esistono finche' non si taggia e
# pubblica la release (vedi i commenti nella recipe stessa). Questo
# script invece compila da questo stesso albero di lavoro e
# impacchetta i binari appena prodotti — comodo per verificare che il
# pacchetto si costruisca e si installi bene PRIMA di taggare la
# release, e per allegare l'hpkg risultante alla release stessa su
# GitHub (stessa procedura gia' usata per v0.1.0).
#
# Uso:
#   packaging/build-hpkg.sh
#
# Il pacchetto risultante va provato con:
#   cp atomo123-0.2.9-1-x86_64.hpkg ~/config/packages/   # solo per l'utente corrente
# oppure, per tutto il sistema (richiede privilegi):
#   cp atomo123-0.2.9-1-x86_64.hpkg /boot/system/packages/
# packagefs lo monta automaticamente, senza bisogno di riavviare.

set -e

cd "$(dirname "$0")/.."
ROOT="$(pwd)"
VERSION="0.2.9-1"
OUT="$ROOT/packaging/atomo123-$VERSION-x86_64.hpkg"
WORKDIR="$ROOT/packaging/hpkg-root"

echo "== Ricompilazione (engine, quattro translator, UI) =="
make -C engine
for t in csv xls xlsx ods; do
	make -C translators/$t
done
make -C ui

echo "== Preparazione dell'albero del pacchetto =="
rm -rf "$WORKDIR"
mkdir -p "$WORKDIR/apps/Atomo123"
mkdir -p "$WORKDIR/add-ons/Translators"
mkdir -p "$WORKDIR/documentation/Atomo123"
cp ui/Atomo123 "$WORKDIR/apps/Atomo123/Atomo123"
cp translators/csv/CsvTranslator "$WORKDIR/add-ons/Translators/"
cp translators/xls/XlsTranslator "$WORKDIR/add-ons/Translators/"
cp translators/xlsx/XlsxTranslator "$WORKDIR/add-ons/Translators/"
cp translators/ods/OdsTranslator "$WORKDIR/add-ons/Translators/"
# File dimostrativo (vedi CHANGELOG.md): "documentation/" e' la
# cartella standard di packagefs per contenuti non eseguibili come
# questo, montata da ogni pacchetto in /boot/system/documentation/.
# MainWindow::kMsgOpenSample (File -> "Apri file di esempio") lo cerca
# in $vendorDataDir (find_directory(B_SYSTEM_DOCUMENTATION_DIRECTORY))
# + "Atomo123/Welcome.xlsx", esattamente questo percorso.
cp packaging/Welcome.xlsx "$WORKDIR/documentation/Atomo123/Welcome.xlsx"

cat > "$WORKDIR/.PackageInfo" <<EOF
name			atomo123
version			$VERSION
architecture		x86_64
summary			"Native spreadsheet for Haiku OS"
description		"Atomo123 is a native, Excel-style spreadsheet application for Haiku OS, written with native APIs (Interface/Layout Kit, Locale Kit, Print Kit, Translation Kit). It is compatible with files generated by Microsoft Excel (XLS/XLSX) and OpenOffice/LibreOffice (ODS/CSV) through Translation Kit conversion add-ons. The calculation engine and the legacy Excel importer reuse and modernize the historical BeOS code of the Sum-It project, ported to build on modern 64-bit Haiku; the UI is written from scratch in Interface/Layout Kit. Includes a demo file (Welcome.xlsx, opened from File -> \"Open Sample File\") with a tour of the main features."
packager		"Andrea Bernardi <atomozero@proton.me>"
vendor			"Andrea Bernardi"
licenses {
	"MIT"
	"BSD (4-clause)"
}
copyrights {
	"2026 Andrea Bernardi"
	"1996-2000 Hekkelman Programmatuur B.V."
}
provides {
	atomo123 = 0.2.9
	app:Atomo123 = 0.2.9
}
requires {
	haiku
}
urls {
	"https://github.com/atomozero/Atomo123"
}
source-urls {
	"https://github.com/atomozero/Atomo123"
}
EOF

echo "== Creazione del pacchetto =="
rm -f "$OUT"
(cd "$WORKDIR" && package create -v "$OUT")

rm -rf "$WORKDIR"

echo
echo "Pacchetto creato: $OUT"
